language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 9
after_success:
  - npm install --no-save semantic-release
  - npx travis-deploy-once "semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
